### ISSUE TITLE
Link for the EGA public key

### ISSUE THREAD

**Issue by jokergoo** [DKFZ-ODCF/ega-cluster-cryptor#1]
URL for the EGA public key in following instruction:

https://github.com/DKFZ-ODCF/ega-cluster-cryptor/blob/93dfce9f6e30ccd3306baab419b69b15d9c07528/1-submit-encryption-jobs.sh#L16

The key cannot be directly copied and used because the format of the key block has been changed in the HTML page. We can use the one in the doc in following link:

https://ega-archive.org/files/EGA_Public_key.doc

**Comment by jokergoo** [comment]
If there is no `EGA_Public_key`, can the script automatically download it?

```
wget https://ega-archive.org/files/EGA_Public_key.doc -O EGA_Public_key
```

`EGA_Public_key.doc` is actually a text file.

**Comment by jokergoo** [comment]
I found it. The `EGA_Public_key` is already shipped with this tool.

**Comment by mmokrejs** [comment]
`gpg --fetch-keys https://ega-archive.org/files/submission_2020_public.gpg.asc`

```
$ gpg --list-key 46A93B8D9F5121C0 
pub   rsa4096 2020-02-17 [SC]
      AF878028FCFAC75C59BC64ED46A93B8D9F5121C0
uid           [ unknown] European Genome-Phenome Archive (EGA) (Submission-key, generated by Jorge Izquierdo 2020) <ega-prod at ebi.ac.uk>
sub   rsa4096 2020-02-17 [E]
$
```
